version: "3.9"

services:
  client:
    build: ./client/
    ports:
      - 8080:8080
    container_name: frontend-docker
    restart: always
    links:
      - server

  server:
    build: ./backend/
    ports:
      - 3000:3000
    container_name: backend-docker
    restart: always

  postgres:
    image: postgres:14-alpine
    ports:
      - 5500:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=mukeshkannan
      - POSTGRES_DB=studystack
