export {default as Home} from './Home'
export {default as Settings} from './Settings'
export {default as AddNew } from './AddNew'
export {default as Profile} from './Profile'
export {default as Revise} from './Revise'
export {default as Signup} from './Signup'
export {default as Login} from './Login'
